site_name: Procom KB
theme:
  name: material
  logo: assets/procom-logo-blanc.png
  favicon: assets/procom-dots.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.top
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: light blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: light blue

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
